name: Deploy Playlists to GitHub Pages

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download latest playlists
      run: |
        echo "📥 Downloading latest playlists..."
        
        # Create docs folder if not exists
        mkdir -p docs
        
        # YuppTV playlist
        curl -s -L -o docs/Yupp.m3u "${{ secrets.YUPPTV_PLAYLIST_URL }}"
        echo "✅ Yupp.m3u downloaded ($(wc -l < docs/Yupp.m3u) lines)"
        
        # CricHD playlists
        curl -s -L -o docs/CricHd.m3u "${{ secrets.CRIC_HD_LIVE }}"
        echo "✅ CricHd.m3u downloaded ($(wc -l < docs/CricHd.m3u) lines)"
        
        # JSON data
        curl -s -L -o docs/api.json "${{ secrets.CRIC_JSON_LIVE }}"
        echo "✅ api.json downloaded ($(wc -c < docs/api.json) bytes)"
        
    - name: Create index page
      run: |
        cat > docs/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Playlists</title>
            <meta charset="utf-8">
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                h1 { color: #333; }
                .file-list { list-style: none; padding: 0; }
                .file-list li { margin: 10px 0; }
                .file-list a { 
                    text-decoration: none; 
                    color: #0366d6; 
                    font-size: 18px;
                    padding: 8px 12px;
                    border: 1px solid #ddd;
                    border-radius: 4px;
                    display: inline-block;
                }
                .file-list a:hover { background: #f6f8fa; }
                .info { color: #666; margin-top: 30px; }
            </style>
        </head>
        <body>
            <h1>📺 Available Playlists</h1>
            <ul class="file-list">
                <li><a href="./Yupp.m3u">YuppTV Playlist (Yupp.m3u)</a></li>
                <li><a href="./CricHd.m3u">CricHD Playlist (CricHd.m3u)</a></li>
                <li><a href="./api.json">API Data (api.json)</a></li>
            </ul>
            <div class="info">
                <p>Last updated: <span id="timestamp">Loading...</span></p>
                <p>Auto-updates every 5 minutes</p>
            </div>
            
            <script>
                document.getElementById('timestamp').textContent = new Date().toLocaleString();
            </script>
        </body>
        </html>
        EOF
        echo "✅ Index page created"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

  status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deployment Status
        run: |
          echo "🎉 Playlists deployed successfully!"
          echo "🌐 Your playlists are now available at:"
          echo "   https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo ""
          echo "📁 Direct links:"
          echo "   Yupp.m3u: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/Yupp.m3u"
          echo "   CricHd.m3u: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/CricHd.m3u"
          echo "   api.json: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/api.json"
